version: "3.11.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  celery:
    container_name: celery
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: sh -c "celery -A config.celery worker --loglevel=INFO -B"
    restart: on-failure
    depends_on:
      - db
      - redis
    env_file: "./.env"

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"
    env_file: "./.env"
    volumes:
      - ./redis/data:/root/redis

  celery-beat:
    build: .
    container_name: celery_beat
    restart: always
    depends_on:
      - db
      - redis
    command: sh -c "celery -A config.celery  beat --loglevel=info"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html

volumes:
  postgres_data:
  static_volume:

