# Generated by Django 5.1.4 on 2025-01-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_user_alter_lesson_user_subscribe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribe",
            name="lesson",
        ),
    ]
