# Generated by Django 5.1.4 on 2025-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="цена"),
        ),
    ]
