# Generated by Django 5.1.4 on 2025-01-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_course_amount_lesson_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
    ]
