# Generated by Django 5.1.4 on 2025-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_remove_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link_on_payment",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
    ]
